version: "3"

services:
    linux_client:
        build: mbed-cloud-client-example

    app:
        build: webapp
        ports:
            - "3000:8080"
        volumes:
            - ./webapp:/usr/src/app
        links:
            - influxdb
            - linux_client
        environment:
            - ENV=development
              #entrypoint: python /usr/src/app/app.py
              #command: python app.py

    influxdb:
        image: influxdb:1.4-alpine
        expose:
            - "8086"
    
    grafana:
        image: grafana/grafana
        ports:
            - "3001:3000"
        links:
            - influxdb
    
